### ISSUE TITLE
[Feature Request] Use Folder Outside of Minecraft

### ISSUE THREAD

**Issue by ardissaps** [DarkRoleplay/Global-Data-and-Resourcepacks#10]
Would you please support global datapack that can be in directory outside of minecraft folder? It will be useful if we have many instance of different minecraft so as example all instance can use datapack from Downloads folder or other folder. Thx in advance sir!

**Comment by JTK222** [comment]
Sorry, this is a huge security risk, I definitely won't allow using anything from the Downloads folder.

However, I could imagine having a global folder for this within your app data folder or similar.
But as this has potential to break a lot of stuff, I can already assure that it'll be locked behind a config option, that hopefully will be disabled in most modpacks by default.

I'll consider it for the next update, but like I said, it's a huge security issue, so I have to think a bit about it.

**Comment by ardissaps** [comment]
> Sorry, this is a huge security risk, I definitely won't allow using anything from the Downloads folder.
> 
> However, I could imagine having a global folder for this within your app data folder or similar. But as this has potential to break a lot of stuff, I can already assure that it'll be locked behind a config option, that hopefully will be disabled in most modpacks by default.
> 
> I'll consider it for the next update, but like I said, it's a huge security issue, so I have to think a bit about it.

Or at least maybe outside instance but still under Launcher folder? (example ATLauncher, so all instance can use same folder as optional datapack folder unified for all Instance)

**Comment by JTK222** [comment]
I can't code something specific for each launcher, especially as mods cannot detect what launcher is used.
Like I said, the only way I can imagine doing this, would be a new folder within your appdata folder.
Or some other specific folder.

**Comment by ardissaps** [comment]
> I can't code something specific for each launcher, especially as mods cannot detect what launcher is used. Like I said, the only way I can imagine doing this, would be a new folder within your appdata folder. Or some other specific folder.

Similiar with this but they dont support datapack, only world save and resource pack
https://modrinth.com/mod/mc-folders

**Comment by JTK222** [comment]
Implemented in v1.14 requires a config value to be set to true, it'll use a global folder that is equal for everyone and cannot be changed.

**Comment by ardissaps** [comment]
> Implemented in v1.14 requires a config value to be set to true, it'll use a global folder that is equal for everyone and cannot be changed.

Which Global folder in windows?

**Comment by JTK222** [comment]
<user home>/.minecraft_global_packs/
I'd recommend to regen the config to get the new setting together with it's explanation.
(Rename the old config launch the game and you get the new one, then you can copy the new entries)
