### ISSUE TITLE
Quilt version crashes

### ISSUE THREAD

**Issue by Trnrr** [DarkRoleplay/Global-Data-and-Resourcepacks#11]
When I load 1.12.2+quilt it crashes. Reproducible with only Global Data and Resource Packs and Quilt.

quilt 0.17.0-beta.2
qsl-1.1.0-beta.14_qfapi-1.0.0-beta.17_fapi-0.54.0_mc-1.18.2

![image](https://user-images.githubusercontent.com/20446954/172035640-5c9e35eb-0b18-48a2-9a50-e4467db89f5d.png)

https://gist.github.com/Trnrr/8141db75b5f1d990da7c6b3dc90a8d52

**Comment by JTK222** [comment]
Fixed in version 1.12.2.1, thank you for reporting this ^^
