### ISSUE TITLE
datapack not loading in 1.19

### ISSUE THREAD

**Issue by Cristelknight999** [DarkRoleplay/Global-Data-and-Resourcepacks#13]
The datapack isn't working, when i use /datapack list it says, that it is loaded, but it doesn't work.

I found that if you click the "Data Packs" button on the World Creation Screen, only then will the datapacks actually work.

**Comment by Cristelknight999** [comment]
The mod version i used is: global_packs-fabric-1.19-1.13_fabric
I tried it with Terralith and WWOO. 
https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/
https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/

**Comment by Cristelknight999** [comment]
![2022-07-11_16 56 23](https://user-images.githubusercontent.com/54945257/178294037-aae6ac29-a4d9-42d8-84fe-297ec597e62b.png)

**Comment by JTK222** [comment]
Fixed in v1.14
