### ISSUE TITLE
Suggestion: Load order setting for datapacks

### ISSUE THREAD

**Issue by Snorps** [DarkRoleplay/Global-Data-and-Resourcepacks#3]
Hi! I'd like to suggest that you add a way to set the order data packs are loaded in when this mod applies them to a new world, this would be really useful for pack devs that want to make modifications to how data packs work without having to distribute someone else's modified work. Thanks!

**Comment by MJRamon** [comment]
I believe you can just name them as 0_datapackname, 1_datapackname and it would work

**Comment by JTK222** [comment]
With the current configs this is possible, you have to specify datapack files rather than folders and can affect their order that way. Packs further down in the config get loaded later.
Therefore I am closing this suggestion as it's implemented.
