### ISSUE TITLE
Cannot Load Multiple Datapacks at the Same Time

### ISSUE THREAD

**Issue by Darkosto** [DarkRoleplay/Global-Data-and-Resourcepacks#6]
Hello!

I've loaded up a 1.18 instance with Global-Data-and-Resourcepacks and have two custom datapacks in the correct folder. For some reason, only 1 of the two datapacks are being loaded. I've been able to load any number of datapacks when creating a world in the past but using the same method I'm unable to do that now. Is there any changes or issues you're aware of when loading multiple datapacks? 

For further info, both datapacks are confirmed valid and functional on their own.

Thank you!
Darkosto

**Comment by JTK222** [comment]
Thank you for reporting, fixed in version 1.9.1 ^^
<https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack/files/3547932>
